# Generated by Django 3.2.5 on 2021-07-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('stock_quantiy', models.IntegerField(default=1)),
                ('rating', models.CharField(choices=[('5 Stars', '5 Stars'), ('4 Stars', '4 Stars'), ('3 Stars', '3 Stars'), ('2 Stars', '2 Stars'), ('1 Stars', '1 Stars')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
